name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: devdojoacademy/githubtemplates/.github/workflows/ecs-service-deploy.yml@main
    with:
      ecr_repository: greetings-service # ab
      aws_region: us-east-1
